name: logger_module
description: "JuneFlow Module for logger"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/logger_module

version: 1.0.0+7

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  logger: ^2.0.2+1 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true