name: logger_module
description: "This is a module that makes it easy to use the logger package."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/logger_module

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  logger:  #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true